*&---------------------------------------------------------------------*
*&  Include           ZRFI_INV_OUTST_02_07_SCR
*&---------------------------------------------------------------------*
*&----------------------Modification Log-------------------------------*
*||Soc by Jash Rajpara   || Neeki Govani    || Devid-5628 || 03-04-2024  || ATDK9A08RG || Value Mismatch-Doc Type & Export Sales Column Add

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: S_BUKRS  FOR GV_BUKRS NO INTERVALS .
PARAMETERS: P_CDATE TYPE DATUM OBLIGATORY DEFAULT SY-DATUM.   "Cut off date

SELECT-OPTIONS: S_PRCTR FOR GV_PRCTR OBLIGATORY . "Profit Center
SELECT-OPTIONS:
S_INVDAT  FOR GV_DATUM DEFAULT SY-DATUM NO-EXTENSION, " Commented SAGAR PATEL
*s_invdat  FOR gv_datum NO-EXTENSION,                  " added by SAGAR PATEL
S_KUNNR FOR GV_KUNNR, "NO INTERVALS NO-EXTENSION,
S_RACCT FOR GV_RACCT.  "Account Number "Added by pratik 8.1.19

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT (31) A1INT FOR FIELD P_INTP.
PARAMETERS : P_INTP TYPE CHAR3 DEFAULT '9'.
SELECTION-SCREEN COMMENT (4) A2INT FOR FIELD P_INTP.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002. " Add on 29-11-2018 by Surajit
PARAMETERS : C1 AS CHECKBOX.
PARAMETERS : C2 AS CHECKBOX.          "" ADDED BY JASH RAJPARA DEV ID: 5628
SELECTION-SCREEN END OF BLOCK B2.

PARAMETERS: PO_VARNT TYPE SY-SLSET NO-DISPLAY.

PARAMETERS : P_BACK AS CHECKBOX.

INITIALIZATION.
  PERFORM SELECTION_SCREEN_TEXT.
